[package]
name = "paracosm-daemon/weaver"
description = "Weaver is an alternative to the lightweight game framework Knit"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	".github",
	".lune",
	".moonwave",
	".vscode",
	"assets",
	"docs",
	"test",
	".gitignore",
	"dev.project.json",
	"moonwave.toml",
	"selene.toml",
	"rokit.toml",
	"LICENSE",
	"CONTRIBUTING.md",
	"README.md"
]

[dependencies]
